services:
  - type: web
    name: jenkins-1
    env: docker
    plan: starter  # You can choose other plans as needed
    dockerfilePath: ./Dockerfile  # Path to your Dockerfile
    dockerContext: .  # Directory containing Dockerfile
    envVars:
      - key: JENKINS_HOME
        value: /var/jenkins_home
    disk:
      name: jenkins_home_1
      mountPath: /var/jenkins_home
      sizeGB: 5  # Adjust as needed

  - type: web
    name: jenkins-2
    env: docker
    plan: starter
    dockerfilePath: ./Jenkins/Dockerfile
    dockerContext: .
    envVars:
      - key: JENKINS_HOME
        value: /var/jenkins_home
    disk:
      name: jenkins_home_2
      mountPath: /var/jenkins_home
      sizeGB: 5

  - type: web
    name: jenkins-3
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: JENKINS_HOME
        value: /var/jenkins_home
    disk:
      name: jenkins_home_3
      mountPath: /var/jenkins_home
      sizeGB: 5
