version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      backend_api:
        condition: service_started
      bst_tree:
        condition: service_started
    networks:
      - cloudrift_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  backend_api:
    build:
      context: .
    container_name: backend_api
    expose:
      - "5000"
    networks:
      - cloudrift_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  bst_tree:
    build:
      context: ../Tree
    container_name: bst_tree
    expose:
      - "5000"
    networks:
      - cloudrift_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: backend_api-jenkins
    expose:
      - "8080"
      - "50000"  # Jenkins agent port
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - TZ=UTC  # Add timezone if needed
    networks:
      - cloudrift_net
    volumes:
      - jenkins-data:/var/jenkins_home  # Persistent volume for Jenkins data
      # Uncomment the following line if Docker access inside Jenkins is needed
      # - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    user: jenkins
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  cloudrift_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  jenkins-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/jenkins-data  # Make sure this directory exists on the host
      o: bind
